name: 🚀 Feature Request
description: 새로운 기능을 제안하세요.
title: "[Feature] 기능 설명 요약"
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ### 🚀 새로운 기능 요청
        원하시는 기능을 설명해주세요.
  - type: input
    id: summary
    attributes:
      label: 기능 요약
      description: "추가하고 싶은 기능을 한 문장으로 설명해주세요."
      placeholder: "예: 사용자 프로필 이미지 업로드 기능 추가"
    validations:
      required: true
  - type: textarea
    id: detailed-description
    attributes:
      label: 기능 설명
      description: "해당 기능이 왜 필요한지 설명해주세요."
      placeholder: "예: 사용자들이 프로필을 설정할 수 있도록 이미지 업로드 기능을 추가하고 싶습니다."
    validations:
      required: true
  - type: dropdown
    id: importance
    attributes:
      label: 중요도
      description: "이 기능이 얼마나 중요한가요?"
      options:
        - 🟢 낮음
        - 🟡 보통
        - 🔴 높음
    validations:
      required: true
